### ISSUE TITLE
element Cg not found

### ISSUE THREAD

**Issue by PyeongKim** [Acellera/moleculekit#55]
I am reading protein.mol2 as an input. However, when I read the file by Molecule, the error comes up.
``
>>> from moleculekit.molecule import Molecule
>>> Molecule("/BiO/pekim/test/1jje/protein.mol2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jlk/anaconda3/envs/LigVoxel/lib/python3.6/site-packages/moleculekit/molecule.py", line 270, in __init__
    self.read(filename, **kwargs)
  File "/home/jlk/anaconda3/envs/LigVoxel/lib/python3.6/site-packages/moleculekit/molecule.py", line 1102, in read
    mol = rr(fname, frame=frame, topoloc=tmppdb, **kwargs)
  File "/home/jlk/anaconda3/envs/LigVoxel/lib/python3.6/site-packages/moleculekit/readers.py", line 588, in MOL2read
    return MolFactory.construct(topologies[0], trajectories[0], filename, frame)
  File "/home/jlk/anaconda3/envs/LigVoxel/lib/python3.6/site-packages/moleculekit/readers.py", line 197, in construct
    uniqueBonds=uniqueBonds,
  File "/home/jlk/anaconda3/envs/LigVoxel/lib/python3.6/site-packages/moleculekit/readers.py", line 330, in _parseTopology
    MolFactory._elementChecks(mol, filename)
  File "/home/jlk/anaconda3/envs/LigVoxel/lib/python3.6/site-packages/moleculekit/readers.py", line 281, in _elementChecks
    el, filename
RuntimeError: Element Cg was read in file /BiO/pekim/test/1jje/protein.mol2 but was not found in the periodictable. To disable this check, pass `validateElements=False` to the Molecule constructor or read method.
``

**Comment by stefdoerr** [comment]
Hi Kim, could you provide me with the file so that I can test it? My assumption is that the mol2 file doesn't have elements and the guessing fails because you have an atom called CG. As the error says, you can disable the check if you want with
`Molecule("/BiO/pekim/test/1jje/protein.mol2", validateElements=False)` but it might be interesting to look at the cause.
