### ISSUE TITLE
Erro with voxelization

### ISSUE THREAD

**Issue by cuzzo87** [Acellera/moleculekit#58]
Hi guys,

I am experiecing some problems in the voxelization procedure. Even following the example, an error is raised.

```python
from htmd.molecule.molecule import Molecule
from moleculekit.tools.voxeldescriptors import getVoxelDescriptors

m = Molecule('3PTB')
m.filter('protein')
features, centers, N = getVoxelDescriptors(m, buffer=8)
```

The error:

```python
  File "current_session.py", line 7, in <module>
    features, centers, N = getVoxelDescriptors(m, buffer=8)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 221, in getVoxelDescriptors
    channels, mol = getChannels(mol, aromaticNitrogen, version, validitychecks)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 106, in getChannels
    mol.atomtype, mol.charge = getPDBQTAtomTypesAndCharges(mol, aromaticNitrogen=aromaticNitrogen, validitychecks=validitychecks)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py", line 222, in getPDBQTAtomTypesAndCharges
    atomtypingValidityChecks(mol)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py", line 196, in atomtypingValidityChecks
    raise ValueError('The protein has less bonds than (number of atoms - 1). This seems incorrect. You can assign bonds with `mol.bonds = mol._getBonds()`')
ValueError: The protein has less bonds than (number of atoms - 1). This seems incorrect. You can assign bonds with `mol.bonds = mol._getBonds()
```

I tried to follow the suggestion about the bonds:

```python
from htmd.molecule.molecule import Molecule
from moleculekit.tools.voxeldescriptors import getVoxelDescriptors

m = Molecule('3PTB')
m.filter('protein')
m.bonds = m._getBonds()
features, centers, N = getVoxelDescriptors(m, buffer=8)
```

The error:

```python
  File "current_session2.py", line 8, in <module>
    features, centers, N = getVoxelDescriptors(m, buffer=8)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 221, in getVoxelDescriptors
    channels, mol = getChannels(mol, aromaticNitrogen, version, validitychecks)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 106, in getChannels
    mol.atomtype, mol.charge = getPDBQTAtomTypesAndCharges(mol, aromaticNitrogen=aromaticNitrogen, validitychecks=validitychecks)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py", line 222, in getPDBQTAtomTypesAndCharges
    atomtypingValidityChecks(mol)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py", line 201, in atomtypingValidityChecks
    raise RuntimeError('The protein has duplicate bond information. This will mess up atom typing. Please keep only unique bonds in the molecule. If you want you can use moleculekit.molecule.calculateUniqueBonds for this.')
RuntimeError: The protein has duplicate bond information. This will mess up atom typing. Please keep only unique bonds in the molecule. If you want you can use moleculekit.molecule.calculateUniqueBonds for this.
```

Ok, as before I tried to follow the suggestion by using *calculateUniqueBonds* (following the example in the method).

```python
from htmd.molecule.molecule import Molecule
from moleculekit.tools.voxeldescriptors import getVoxelDescriptors
from moleculekit.molecule import calculateUniqueBonds

m = Molecule('3PTB')
m.filter('protein')
m.bonds, m.bondtype = calculateUniqueBonds(m.bonds, m.bondtype)
features, centers, N = getVoxelDescriptors(m, buffer=8)
```

The error:

```python 
Traceback (most recent call last):
  File "current_session3.py", line 9, in <module>
    features, centers, N = getVoxelDescriptors(m, buffer=8)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 221, in getVoxelDescriptors
    channels, mol = getChannels(mol, aromaticNitrogen, version, validitychecks)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/voxeldescriptors.py", line 106, in getChannels
    mol.atomtype, mol.charge = getPDBQTAtomTypesAndCharges(mol, aromaticNitrogen=aromaticNitrogen, validitychecks=validitychecks)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py", line 222, in getPDBQTAtomTypesAndCharges
    atomtypingValidityChecks(mol)
  File "/home/alberto/Software/miniconda3/envs/htmd/lib/python3.6/site-packages/moleculekit/tools/atomtyper.py", line 196, in atomtypingValidityChecks
    raise ValueError('The protein has less bonds than (number of atoms - 1). This seems incorrect. You can assign bonds with `mol.bonds = mol._getBonds()`')
ValueError: The protein has less bonds than (number of atoms - 1). This seems incorrect. You can assign bonds with `mol.bonds = mol._getBonds()
```

Do you have any suggestion?

**Comment by stefdoerr** [comment]
Take a look at the voxelization tutorial https://software.acellera.com/docs/latest/moleculekit/tutorials/voxelization_tutorial.html
You are missing a crucial step which is protein preparation for atom typing.

**Comment by Spartanzhao** [comment]
> Take a look at the voxelization tutorial https://software.acellera.com/docs/latest/moleculekit/tutorials/voxelization_tutorial.html
> You are missing a crucial step which is protein preparation for atom typing.

Next time, can you just directly tell us which command line solve the issue, because the link is invalid and tutorial doesn't directly tell me which command line can deal with this error.

**Comment by giadefa** [comment]
Here it is. We have recently changed the doc structure. You must read the
tutorial to use it correctly.
https://software.acellera.com/moleculekit/tutorials/voxelization_tutorial.html
